### PR TITLE
feat: merge MAIF and Fing steps

### PR DESCRIPTION
**Pull request by gregorylegarec**

### CODE REVIEW

**Review by CPatchane — APPROVED** [review]
Seems good to me 👍 but there is a conflict. Thanks to rebase it in order to merge it.

**Comment by gregorylegarec** [comment]
@CPatchane I will rebase, and I still need to change Orange to Orange VOD.

**Comment by gregorylegarec** [comment]
@CPatchane Ok, rebased and ready to merge. I added one commit to split Orange service between OrangeMobile and OrangeVOD.

**Comment by CPatchane** [comment]
Thanks @gregorylegarec!

**Pull request merged**
