### PR TITLE
Feat/new design

### PR DESCRIPTION
**Pull request by GoOz**
- [x] Updated Font family to Lato
- [x] New blue color
- [x] Higher buttons
- [x] Input's background is now white
- [x] New step number indicator
- [x] New icon on welcome page
- [x] Replaced show/hide password's icon button with textual button
- [x] New content and image for accounts step
- [x] Updated text on last step

### CODE REVIEW

**Comment by GoOz** [comment]
[(2) [ONB-9 / E-33] ETU mon onboarding est cohérent avec mon Cozy v3](https://trello.com/c/ddUgNOfc/286-2-onb-9-e-33-etu-mon-onboarding-est-coherent-avec-mon-cozy-v3)

**Review by gregorylegarec — APPROVED** [review]
Looks ok to me 👍

**Comment by gregorylegarec** [comment]
Actually, I just have one remark: maybe the `h1` elements should not have `font-weight: bold` property.

Have a look at the following screenshots and tell me what do you think :
Mockup :
capture d ecran 2017-04-04 a 17 25 22

Without  `font-weight: bold` 
capture d ecran 2017-04-04 a 17 25 59

With `font-weight: bold` 
capture d ecran 2017-04-04 a 17 26 11

Firefox is more sensitive about `font-weight`, this is what `font-weight: 300` looks like:

capture d ecran 2017-04-04 a 17 29 04

What do you think ? ping @kelukelu

**Comment by GoOz** [comment]
@gregorylegarec Funny, my Firefox doesn't render like this… at all.
with `font-weight: normal`
screen shot 2017-04-04 at 17 36 01

with `font-weight: bold`
screen shot 2017-04-04 at 17 36 14

**Comment by kelukelu** [comment]
I will keep the bold. It allows a better understanding of the title.
However, I noticed an issue with the `line-height` of the content below (it should be `line-height: 1.5` if `1em = 16px`). 
Also I think the space between the two paragraphs brings complexity to read it.

**Comment by GoOz** [comment]
@kelukelu Duly noted. 
But just to be clear, there's a `line-height 1.15` on the HTML element, should i change it to 1.5 on the HTML element too, which will change the line-height of every element (with no line-height specified)? or do you want me to change the line-height only on paragraphs? 
Kinda same question for `<p>`'s margin, only those paragraphs in this step or every paragraphs in every step?

**Comment by kelukelu** [comment]
@GoOz the `line-height = 1.5` should be added just to `<p>` elements. 
You can remove the margin on `<p>` too. I just had a look to the marvel, on their is no margin on paragraphs.

**Comment by GoOz** [comment]
@kelukelu deal! 😄

**Comment by gregorylegarec** [comment]
Thanks @GoOz  !

**Pull request merged**
